### ISSUE TITLE
How to override user agent?

### ISSUE THREAD

**Issue by derwaldgeist** [edgafner/GIdeaBrowser#76]
I tried to override the UserAgent header for a specific page, but to no avail. Is this possible somehow? 

![image](https://github.com/edgafner/GIdeaBrowser/assets/3984535/a963cc49-a41d-4205-a40a-864120f25eff)

**Comment by Jonatha1983** [comment]
@Majed6 hi, any chance you can check this?

**Comment by Jonatha1983** [comment]
Seems to be solved will close this ticket. 

Thanks @Majed6
